version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - API_URL=${API_URL:-http://host.docker.internal:8080}
    extra_hosts:
      - "host.docker.internal:host-gateway"
