export const TRANSACTION_STATUS_TYPES = {
  NEW: "NEW",
  CONFIRMED: "CONFIRMED",
  PROCESSING: "PROCESSING",
  CANCELED: "CANCELED",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
  RETURNED: "RETURNED",
}

const PERSON_TYPES_NAMES = {
  PHYSICAL: 'PHYSICAL',
  LEGAL: 'LEGAL',
};

export const PERSON_TYPES = {
  [PERSON_TYPES_NAMES.PHYSICAL]: "Физическое лицо",
  [PERSON_TYPES_NAMES.LEGAL]: "Юридическое лицо",
};


